### ISSUE TITLE
Differences between redux and dutier

### ISSUE THREAD

**Issue by thiamsantos** [luisvinicius167/dutier#3]
What are the main differences between dutier and redux?

**Comment by luisvinicius167** [comment]
I think `Dutier` shares the same principles that `Redux`, actions that return payloads that says how to work with the state without change them, just returning new values usign the initial state.

Dutier reducers always have the initial state as first argument. The `createStore` methods returns nothing, and the `dispatch` methods always returns a Promise with the action type and the new state value.

Dutier has a tiny size (1.5kb), tiny API and it's very easy to get started with React, Vue, Preact, any Frameworks.

**Comment by piyushchauhan2011** [comment]
Are there any pattern for making `api` requests ? like using `async` and `await` and updating the state like we do in Redux Saga ? @luisvinicius167 

It looks great, tiny and relevant 💯

**Comment by luisvinicius167** [comment]
@piyushchauhan2011 I'll provide some examples with api requests, but I think you can make an api request inside your component and them dispatch an action with response, chaining your dispatch and then update the component state with the new state value, returned by dispatch method. But the fetch will be present inside your component, not in your actions..

**Comment by developit** [comment]
Seems like the biggest difference is that dutier is a singleton?

**Comment by luisvinicius167** [comment]
@developit yeah! So, it's because dutier createStore just sets the initialState and the reducers will return new state values and update the current state. With this, you don't need to pass a store instance over your  components... Thanks for comment!

**Comment by luisvinicius167** [comment]
Dutier v0.0.3 available now! Thanks folks!
