### ISSUE TITLE
Async Reducers

### ISSUE THREAD

**Issue by gingur** [luisvinicius167/dutier#8]
Using your example https://codesandbox.io/s/1AyKXMpG, how would I handle getting state during an async reducer?

```js
case 'INCREMENT':
  // async operation
  setTimeout( () => {
    dispatch({ count: store.getState().count + 1 })
  }, value);
```

Using something like the above would be anti-pattern I'm guessing, wouldn't it make more sense to only perform async operations in the actions, and not the reducers?

**Comment by luisvinicius167** [comment]
Hi @gingur,  yeah, I'm was working in that concept. v0.6.0 available! Check out the documentation. Thanks!
